sonar.projectKey=webta
sonar.projectName=Project Tawell
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**,.next/**,dist/**

sonar.host.url=http://localhost:9000
sonar.token=sqp_1bf73abbdb28b8fb7f05c565038a7d57f759fba6


"set NODE_OPTIONS=--max-old-space-size=4096 && set NEXT_DISABLE_WORKER=1 && set NEXT_TELEMETRY_DISABLED=1 && next build"



