/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KoiCert } from "./KoiCert";
export * as factories from "./factories";
export { KoiCert__factory } from "./factories/KoiCert__factory";
