/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace KoiCert {
  export type KoiDataStruct = {
    id: string;
    variety: string;
    breeder: string;
    gender: string;
    age: string;
    size: BigNumberish;
    condition: string;
    photoUrl: string;
    certUrl: string;
    contestUrl: string;
    timestamp: BigNumberish;
    issuer: AddressLike;
  };

  export type KoiDataStructOutput = [
    id: string,
    variety: string,
    breeder: string,
    gender: string,
    age: string,
    size: bigint,
    condition: string,
    photoUrl: string,
    certUrl: string,
    contestUrl: string,
    timestamp: bigint,
    issuer: string
  ] & {
    id: string;
    variety: string;
    breeder: string;
    gender: string;
    age: string;
    size: bigint;
    condition: string;
    photoUrl: string;
    certUrl: string;
    contestUrl: string;
    timestamp: bigint;
    issuer: string;
  };
}

export interface KoiCertInterface extends Interface {
  getFunction(
    nameOrSignature: "getKoi" | "koiRegistry" | "mintCertificate"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "KoiMinted"): EventFragment;

  encodeFunctionData(functionFragment: "getKoi", values: [string]): string;
  encodeFunctionData(functionFragment: "koiRegistry", values: [string]): string;
  encodeFunctionData(
    functionFragment: "mintCertificate",
    values: [
      string,
      string,
      string,
      string,
      string,
      BigNumberish,
      string,
      string,
      string,
      string
    ]
  ): string;

  decodeFunctionResult(functionFragment: "getKoi", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "koiRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintCertificate",
    data: BytesLike
  ): Result;
}

export namespace KoiMintedEvent {
  export type InputTuple = [id: string, variety: string, issuer: AddressLike];
  export type OutputTuple = [id: string, variety: string, issuer: string];
  export interface OutputObject {
    id: string;
    variety: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KoiCert extends BaseContract {
  connect(runner?: ContractRunner | null): KoiCert;
  waitForDeployment(): Promise<this>;

  interface: KoiCertInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getKoi: TypedContractMethod<
    [_id: string],
    [KoiCert.KoiDataStructOutput],
    "view"
  >;

  koiRegistry: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        string
      ] & {
        id: string;
        variety: string;
        breeder: string;
        gender: string;
        age: string;
        size: bigint;
        condition: string;
        photoUrl: string;
        certUrl: string;
        contestUrl: string;
        timestamp: bigint;
        issuer: string;
      }
    ],
    "view"
  >;

  mintCertificate: TypedContractMethod<
    [
      _id: string,
      _variety: string,
      _breeder: string,
      _gender: string,
      _age: string,
      _size: BigNumberish,
      _condition: string,
      _photoUrl: string,
      _certUrl: string,
      _contestUrl: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getKoi"
  ): TypedContractMethod<[_id: string], [KoiCert.KoiDataStructOutput], "view">;
  getFunction(
    nameOrSignature: "koiRegistry"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        string
      ] & {
        id: string;
        variety: string;
        breeder: string;
        gender: string;
        age: string;
        size: bigint;
        condition: string;
        photoUrl: string;
        certUrl: string;
        contestUrl: string;
        timestamp: bigint;
        issuer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintCertificate"
  ): TypedContractMethod<
    [
      _id: string,
      _variety: string,
      _breeder: string,
      _gender: string,
      _age: string,
      _size: BigNumberish,
      _condition: string,
      _photoUrl: string,
      _certUrl: string,
      _contestUrl: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "KoiMinted"
  ): TypedContractEvent<
    KoiMintedEvent.InputTuple,
    KoiMintedEvent.OutputTuple,
    KoiMintedEvent.OutputObject
  >;

  filters: {
    "KoiMinted(string,string,address)": TypedContractEvent<
      KoiMintedEvent.InputTuple,
      KoiMintedEvent.OutputTuple,
      KoiMintedEvent.OutputObject
    >;
    KoiMinted: TypedContractEvent<
      KoiMintedEvent.InputTuple,
      KoiMintedEvent.OutputTuple,
      KoiMintedEvent.OutputObject
    >;
  };
}
